//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allergies
    {
        public int AllergyID { get; set; }
        public int PatientIdCPCL { get; set; }
        public string ATCCode { get; set; }
        public Nullable<int> ArtID { get; set; }
    }
}
