//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        public int AnalysisNr { get; set; }
        public System.DateTime BuyDate { get; set; }
        public Nullable<System.DateTime> DateAnalysis { get; set; }
        public Nullable<decimal> Qtd { get; set; }
        public string UnitCode { get; set; }
        public string LotNr { get; set; }
        public string LotNrSuffix { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public int ArtID { get; set; }
        public int SupplierIDSupplier { get; set; }
        public int SupplierIDManuf { get; set; }
        public string AuthorisNr { get; set; }
        public string PhcopeeType { get; set; }
        public string Report { get; set; }
        public Nullable<short> IsConform { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateEmpty { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public string Location { get; set; }
        public Nullable<int> ArtIDTsp { get; set; }
        public string AnalysisStatusType { get; set; }
    }
}
