//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chemicals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chemicals()
        {
            this.ChemicalNames = new HashSet<ChemicalNames>();
        }
    
        public int ArtIdCPCL { get; set; }
        public string CNKNr { get; set; }
        public Nullable<decimal> PubPrice { get; set; }
        public string VatCode { get; set; }
        public int StockMngmntType { get; set; }
        public short HasExpiry { get; set; }
        public Nullable<short> IsPrintLabel { get; set; }
        public string StorageType { get; set; }
        public Nullable<decimal> BuyPriceCalc { get; set; }
        public string BuyPriceSrc { get; set; }
        public string ApbUdStatusCode { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
        public string AllowUdPubPriceChangeType { get; set; }
        public string ApbCatCode { get; set; }
        public string ApbLegCode { get; set; }
        public string EanNr { get; set; }
        public string AvailabilityCode { get; set; }
        public Nullable<decimal> EffectiveBuyPrice { get; set; }
        public Nullable<short> IsReimbHomeo { get; set; }
        public Nullable<int> TherapUseID { get; set; }
        public string StupNr { get; set; }
        public short HasLocation { get; set; }
        public Nullable<short> IsOxygen { get; set; }
        public Nullable<short> IsSubstitutionTreatment { get; set; }
        public string ArtType { get; set; }
        public string InvCatCode { get; set; }
        public string Memo { get; set; }
        public Nullable<int> GreenockID { get; set; }
        public Nullable<int> ArtCID { get; set; }
        public string ChemicalType { get; set; }
        public decimal ChemPricePerUnit { get; set; }
        public Nullable<decimal> Qtd { get; set; }
        public string UnitCode { get; set; }
        public string PriceSource { get; set; }
        public decimal Density { get; set; }
        public string PlantCode { get; set; }
        public Nullable<decimal> DefaultPresbQtd { get; set; }
        public string UnitCodeDefaultPresb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChemicalNames> ChemicalNames { get; set; }
    }
}
