//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPCLEntities : DbContext
    {
        public CPCLEntities()
            : base("name=CPCLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergies> Allergies { get; set; }
        public virtual DbSet<Attestations> Attestations { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<InsrCovers> InsrCovers { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<Pathologies> Pathologies { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Pharmacies> Pharmacies { get; set; }
        public virtual DbSet<PlaceLabels> PlaceLabels { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Prescribers> Prescribers { get; set; }
        public virtual DbSet<RistCards> RistCards { get; set; }
        public virtual DbSet<RistCardsAccounts> RistCardsAccounts { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<ArtNames> ArtNames { get; set; }
        public virtual DbSet<ChemicalNames> ChemicalNames { get; set; }
        public virtual DbSet<Chemicals> Chemicals { get; set; }
        public virtual DbSet<HvtNames> HvtNames { get; set; }
        public virtual DbSet<HvtQtyPrices> HvtQtyPrices { get; set; }
        public virtual DbSet<Hvts> Hvts { get; set; }
        public virtual DbSet<IdealStockThresholds> IdealStockThresholds { get; set; }
        public virtual DbSet<LabelEditorArticles> LabelEditorArticles { get; set; }
        public virtual DbSet<LabelEditorLocs> LabelEditorLocs { get; set; }
        public virtual DbSet<Localization> Localization { get; set; }
        public virtual DbSet<LocalizationStock> LocalizationStock { get; set; }
        public virtual DbSet<MultidoseLinks> MultidoseLinks { get; set; }
        public virtual DbSet<Peremption> Peremption { get; set; }
        public virtual DbSet<Statistic> Statistic { get; set; }
        public virtual DbSet<StockLog> StockLog { get; set; }
        public virtual DbSet<Stocks> Stocks { get; set; }
        public virtual DbSet<TherapUses> TherapUses { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
        public virtual DbSet<AppVersions> AppVersions { get; set; }
        public virtual DbSet<ComplementaryMention> ComplementaryMention { get; set; }
        public virtual DbSet<Counters> Counters { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<CPCLParamValues> CPCLParamValues { get; set; }
        public virtual DbSet<CPCLTables> CPCLTables { get; set; }
        public virtual DbSet<CustRistGroupLabels> CustRistGroupLabels { get; set; }
        public virtual DbSet<CustRistGroups> CustRistGroups { get; set; }
        public virtual DbSet<GenderCode> GenderCode { get; set; }
        public virtual DbSet<GreenockUsers> GreenockUsers { get; set; }
        public virtual DbSet<MagType> MagType { get; set; }
        public virtual DbSet<OldSoftTableNames> OldSoftTableNames { get; set; }
        public virtual DbSet<ParameterLabels> ParameterLabels { get; set; }
        public virtual DbSet<ParameterTypes> ParameterTypes { get; set; }
        public virtual DbSet<PaymMethods> PaymMethods { get; set; }
        public virtual DbSet<PharmDocDataLabels> PharmDocDataLabels { get; set; }
        public virtual DbSet<PharmDocDatas> PharmDocDatas { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<ProfileTypes> ProfileTypes { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<RegulationType> RegulationType { get; set; }
        public virtual DbSet<RoleLabels> RoleLabels { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TaskGroupLabels> TaskGroupLabels { get; set; }
        public virtual DbSet<TaskGroupTypes> TaskGroupTypes { get; set; }
        public virtual DbSet<TaskLabels> TaskLabels { get; set; }
        public virtual DbSet<TaskTypes> TaskTypes { get; set; }
        public virtual DbSet<ToVerify> ToVerify { get; set; }
        public virtual DbSet<ToVerifyLabel> ToVerifyLabel { get; set; }
        public virtual DbSet<Trace> Trace { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
        public virtual DbSet<TypeNote> TypeNote { get; set; }
        public virtual DbSet<UnitCode> UnitCode { get; set; }
        public virtual DbSet<UserEmails> UserEmails { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<CustRistGroupLabels1> CustRistGroupLabels1 { get; set; }
        public virtual DbSet<CustRistGroups1> CustRistGroups1 { get; set; }
        public virtual DbSet<MarginTypes> MarginTypes { get; set; }
        public virtual DbSet<Registers> Registers { get; set; }
        public virtual DbSet<RistCustArticles> RistCustArticles { get; set; }
        public virtual DbSet<RistCustRistGroups> RistCustRistGroups { get; set; }
        public virtual DbSet<RistCustRules> RistCustRules { get; set; }
        public virtual DbSet<RistPatRistGroups> RistPatRistGroups { get; set; }
        public virtual DbSet<UrlTypes> UrlTypes { get; set; }
        public virtual DbSet<WhLocationLabels> WhLocationLabels { get; set; }
        public virtual DbSet<WhLocs> WhLocs { get; set; }
        public virtual DbSet<WorkstationDevices> WorkstationDevices { get; set; }
        public virtual DbSet<Workstations> Workstations { get; set; }
        public virtual DbSet<WrkstatBackups> WrkstatBackups { get; set; }
        public virtual DbSet<WrkstatBarcodeReaders> WrkstatBarcodeReaders { get; set; }
        public virtual DbSet<WrkstatCashDrawers> WrkstatCashDrawers { get; set; }
        public virtual DbSet<WrkstatEfts> WrkstatEfts { get; set; }
        public virtual DbSet<WrkstatEidReaders> WrkstatEidReaders { get; set; }
        public virtual DbSet<WrkstatModems> WrkstatModems { get; set; }
        public virtual DbSet<WrkstatPaperScans> WrkstatPaperScans { get; set; }
        public virtual DbSet<WrkstatPrinters> WrkstatPrinters { get; set; }
        public virtual DbSet<WrkstatRobots> WrkstatRobots { get; set; }
        public virtual DbSet<WrkstatScreens> WrkstatScreens { get; set; }
        public virtual DbSet<WrkstatSisReaders> WrkstatSisReaders { get; set; }
        public virtual DbSet<Analysis> Analysis { get; set; }
        public virtual DbSet<FormulaItems> FormulaItems { get; set; }
        public virtual DbSet<FormulaLabels> FormulaLabels { get; set; }
        public virtual DbSet<Formulas> Formulas { get; set; }
        public virtual DbSet<InvCatBreakds> InvCatBreakds { get; set; }
        public virtual DbSet<PaymEftBreakds> PaymEftBreakds { get; set; }
        public virtual DbSet<PaymMethodBreakds> PaymMethodBreakds { get; set; }
        public virtual DbSet<PaymMethodLabels> PaymMethodLabels { get; set; }
        public virtual DbSet<PaymMethods1> PaymMethods1 { get; set; }
        public virtual DbSet<Registers1> Registers1 { get; set; }
        public virtual DbSet<RegSessions> RegSessions { get; set; }
        public virtual DbSet<RegTransactions> RegTransactions { get; set; }
        public virtual DbSet<WithdDeps> WithdDeps { get; set; }
        public virtual DbSet<WithdDepTypes> WithdDepTypes { get; set; }
        public virtual DbSet<Magistrals> Magistrals { get; set; }
        public virtual DbSet<MagItems> MagItems { get; set; }
        public virtual DbSet<RistCardsRists> RistCardsRists { get; set; }
        public virtual DbSet<SaleItems> SaleItems { get; set; }
        public virtual DbSet<SaleItemType> SaleItemType { get; set; }
        public virtual DbSet<SalePoso> SalePoso { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<SaleSections> SaleSections { get; set; }
        public virtual DbSet<SaleSectionType> SaleSectionType { get; set; }
        public virtual DbSet<SitmHons> SitmHons { get; set; }
        public virtual DbSet<SitmUbcs> SitmUbcs { get; set; }
        public virtual DbSet<SpecHonCode> SpecHonCode { get; set; }
        public virtual DbSet<ReturnAwaitings> ReturnAwaitings { get; set; }
        public virtual DbSet<ProductInOrder> ProductInOrder { get; set; }
        public virtual DbSet<PrgRecupVersion> PrgRecupVersion { get; set; }
        public virtual DbSet<ProfileLabels> ProfileLabels { get; set; }
        public virtual DbSet<Actor_Pharmacies> Actor_Pharmacies { get; set; }
        public virtual DbSet<BarcodeReaderTypes> BarcodeReaderTypes { get; set; }
        public virtual DbSet<Params> Params { get; set; }
    }
}
