//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int CreditId { get; set; }
        public int PatIdCPCL { get; set; }
        public System.DateTime DateSale { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> SlsID { get; set; }
        public string CreditType { get; set; }
        public Nullable<int> GreenockId { get; set; }
    }
}
