//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int CustomerIdCPCL { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string GSM { get; set; }
        public string Email { get; set; }
        public string VatNr { get; set; }
        public string BankAccNr { get; set; }
        public string langCode { get; set; }
        public Nullable<int> GreenockID { get; set; }
        public string Memo { get; set; }
        public string CustRistGrpCode { get; set; }
        public string PharmApbNr { get; set; }
        public string PaymMethodType { get; set; }
        public Nullable<short> IsIvc { get; set; }
        public Nullable<short> IsMultidose { get; set; }
        public string RefHomeLink { get; set; }
        public string AccountingId { get; set; }
    }
}
