//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustRistGroups1
    {
        public string CustRistGrpCode { get; set; }
        public Nullable<short> IsPatient { get; set; }
        public string DefaultRistType { get; set; }
        public Nullable<System.DateTime> DateLastChange { get; set; }
        public Nullable<byte> Deleted { get; set; }
    }
}
