//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmadContainer : DbContext
    {
        public FarmadContainer()
            : base("name=FarmadContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FTBADRESSEN> FTBADRESSEN { get; set; }
        public virtual DbSet<FTBKLANTEN> FTBKLANTEN { get; set; }
        public virtual DbSet<FTBKLANTSIS> FTBKLANTSIS { get; set; }
        public virtual DbSet<FTBTELNUMMERS> FTBTELNUMMERS { get; set; }
        public virtual DbSet<FTBPOSTCODES> FTBPOSTCODES { get; set; }
        public virtual DbSet<FTBPRODUCTEN> FTBPRODUCTEN { get; set; }
        public virtual DbSet<FTBPRODUCTSTOCK> FTBPRODUCTSTOCK { get; set; }
        public virtual DbSet<FTBVERKOPEN> FTBVERKOPEN { get; set; }
        public virtual DbSet<FTBVERKOOPITEMS> FTBVERKOOPITEMS { get; set; }
    }
}
