//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulaLabels
    {
        public int FormID { get; set; }
        public string LangCode { get; set; }
        public string FormulariumLabel { get; set; }
        public Nullable<int> FormulariumLabelNr { get; set; }
    
        public virtual Formulas Formulas { get; set; }
    }
}
