//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulaItems
    {
        public int FormID { get; set; }
        public int FormItemNr { get; set; }
        public string FormItemType { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> Qtd { get; set; }
        public string UnitCode { get; set; }
        public Nullable<int> ArtID { get; set; }
        public string SpecHonCode { get; set; }
        public int QtyQualifier { get; set; }
        public Nullable<int> GreenockID { get; set; }
    
        public virtual Formulas Formulas { get; set; }
    }
}
