//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBADRESSEN
    {
        public int A_UID { get; set; }
        public Nullable<int> A_OBJECTNUMMER { get; set; }
        public string A_KAMERNUMMER { get; set; }
        public string A_STRAAT { get; set; }
        public string A_LAND { get; set; }
        public Nullable<int> A_PC_ID { get; set; }
        public string A_TYPE { get; set; }
        public string A_ISFACTURATIEADRES { get; set; }
        public string A_OBJECT_TYPE { get; set; }
    }
}
