//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBKLANTEN
    {
        public int K_KLANTNUMMER { get; set; }
        public string K_FAMILIENAAM { get; set; }
        public string K_VOORNAAM { get; set; }
        public Nullable<int> K_ARTSNUMMER { get; set; }
        public string K_704 { get; set; }
        public string K_AFSCHRIFT { get; set; }
        public Nullable<System.DateTime> K_LAATSTE_BEZOEK { get; set; }
        public string K_SOUNDEX { get; set; }
        public string K_RIJKSWACHT { get; set; }
        public string K_DOSSIERNUMMER { get; set; }
        public Nullable<int> K_WGID { get; set; }
        public string K_IS_DUMMY { get; set; }
        public string K_ZOEK { get; set; }
        public Nullable<int> K_FACTGROEP { get; set; }
        public string K_EERSTE_AFLEV { get; set; }
        public string K_INTER_TONEN { get; set; }
        public string K_POS_TONEN { get; set; }
        public string K_EMAIL_ADRES { get; set; }
        public string K_HEEFT_KREDIET { get; set; }
        public string K_BTWNUMMER { get; set; }
        public string K_HEEFT_UNIX_KREDIET { get; set; }
        public string K_GESCHRAPT { get; set; }
        public Nullable<int> K_KSID { get; set; }
        public string K_VOL_NAAM { get; set; }
        public string K_ISVETERINAIR { get; set; }
        public string K_TAALCODE { get; set; }
        public string K_GEBRUIKT_KORTTABEL { get; set; }
        public Nullable<int> K_FAMILIE_ID { get; set; }
        public string K_SPAARKAARTID { get; set; }
        public string K_INSZ { get; set; }
        public string K_TAAL_CBL { get; set; }
        public Nullable<int> K_MUT2_SOORT { get; set; }
        public string K_MUT2_STAMNUMMER { get; set; }
        public string K_MEDSEINVOORKEUR { get; set; }
        public string K_GEENKORTING { get; set; }
        public Nullable<int> K_SCHEMAID { get; set; }
        public string K_GEENPROMO { get; set; }
        public string K_VOLNAAM { get; set; }
        public Nullable<decimal> K_KORTINGSPERCENT { get; set; }
        public Nullable<int> K_DEFAULT_ADRES_ID { get; set; }
        public string K_TEKST { get; set; }
        public Nullable<int> K_NEWKSID { get; set; }
        public string K_UDROBOT { get; set; }
        public string K_EXTSTOCK { get; set; }
        public string K_DIABETES_NIETMEERTONEN { get; set; }
        public string K_LEEFGROEP { get; set; }
        public string K_CONTACTNR { get; set; }
        public string K_OVERLEDEN { get; set; }
        public Nullable<System.DateTime> K_OVERLEDEN_DATUM { get; set; }
        public string K_EMAIL_ADRES_GEBRUIKEN { get; set; }
        public string K_EMAIL_ADRES2 { get; set; }
        public string K_EMAIL_ADRES2_GEBRUIKEN { get; set; }
        public string K_PARASTATAAL { get; set; }
        public Nullable<int> K_DEFAULT_TEL_ID { get; set; }
        public string K_MUT2_CAT { get; set; }
        public string K_GFD_CONSENT { get; set; }
        public Nullable<int> K_MST_GEDETAILLEERD_OVERZICHT { get; set; }
        public Nullable<int> K_MST_DAGSCHEMA { get; set; }
        public Nullable<int> K_MST_DAGSCHEMA_WEEK { get; set; }
        public Nullable<int> K_MST_WEEKSCHEMA { get; set; }
        public Nullable<int> K_MST_MAANDSCHEMA { get; set; }
        public string K_PASSANT { get; set; }
        public string K_KORTVERBLIJVER { get; set; }
        public Nullable<System.DateTime> K_CONSENTREFUSEDON { get; set; }
    }
}
