//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBKLANTSIS
    {
        public int KS_ID { get; set; }
        public Nullable<int> KS_KLANTNUMMER { get; set; }
        public Nullable<int> KS_MUT { get; set; }
        public string KS_CG1 { get; set; }
        public string KS_CG2 { get; set; }
        public string KS_CATEGORIE { get; set; }
        public string KS_STAMNUMMER { get; set; }
        public Nullable<System.DateTime> KS_SIS_GELEZEN { get; set; }
        public string KS_NR_SIS { get; set; }
        public string KS_VERSIE_VERZ { get; set; }
        public string KS_CERTIFICAAT { get; set; }
        public Nullable<System.DateTime> KS_SISGELDIGHEID { get; set; }
        public Nullable<int> KS_SISLEZERID { get; set; }
        public Nullable<short> KS_GESLACHT { get; set; }
        public Nullable<System.DateTime> KS_GEBOORTEDATUM { get; set; }
        public string KS_FAMILIENAAM { get; set; }
        public string KS_VOORNAAM { get; set; }
        public string KS_VOL_MUT { get; set; }
        public string KS_CG1CG2 { get; set; }
        public string KS_VOL_NAAM { get; set; }
        public string KS_ATTEST { get; set; }
        public Nullable<int> KS_LEEFTIJD_IN_MND { get; set; }
        public string KS_CONTACTNR { get; set; }
        public string KS_CONTROLECODE_TD { get; set; }
        public string KS_TYPE { get; set; }
        public Nullable<System.DateTime> KS_DATUM_START { get; set; }
        public string KS_PA_SEED { get; set; }
        public Nullable<long> KS_LEEFTIJD { get; set; }
        public Nullable<System.DateTime> KS_DATUM_OVERLIJDEN { get; set; }
        public string KS_RIZIVNR_WZC { get; set; }
        public string KS_GEHOSPITALISEERD { get; set; }
        public string KS_PHARMA_CHECKDIGIT { get; set; }
        public string KS_INSZ { get; set; }
    }
}
