//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBPRODUCTSTOCK
    {
        public string PS_CNKNUMMER { get; set; }
        public int PS_INSTOCK { get; set; }
        public Nullable<System.DateTime> PS_LAATSTVERKOCHT { get; set; }
        public Nullable<System.DateTime> PS_LAATSTBESTELD { get; set; }
        public string PS_DUBBELESTOCK { get; set; }
        public Nullable<short> PS_MIN_APOTHEEK { get; set; }
        public Nullable<short> PS_MAX_APOTHEEK { get; set; }
        public Nullable<short> PS_BUFFER_STOCK { get; set; }
        public Nullable<long> PS_APOTHEEK_STOCK { get; set; }
        public int PS_BESTELPOLITIEK { get; set; }
        public int PS_BESTELKLASSE { get; set; }
    }
}
