//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBPRODUCTEN
    {
        public string P_CNKNUMMER { get; set; }
        public Nullable<decimal> P_PRIJS { get; set; }
        public Nullable<decimal> P_VORIGE_PUBPRIJS { get; set; }
        public Nullable<int> P_MAN_BHOEVEELHEID { get; set; }
        public Nullable<decimal> P_VERKOOPPRIJS { get; set; }
        public Nullable<int> P_BTW_VERKOOP { get; set; }
        public string P_KODE_VVD { get; set; }
        public Nullable<System.DateTime> P_DAT_CREATIE { get; set; }
        public Nullable<System.DateTime> P_SCHRAPDATUM { get; set; }
        public Nullable<System.DateTime> P_VERVALDATUM { get; set; }
        public Nullable<short> P_TYPE_PRODUCT { get; set; }
        public string P_WETTELIJKE_CODE { get; set; }
        public Nullable<short> P_TYPE_VERKPRIJS { get; set; }
        public string P_VERKOOPSVORM { get; set; }
        public string P_TMBLINK { get; set; }
        public string P_AUTO_BPOLITIEK { get; set; }
        public string P_BEWAARCODE { get; set; }
        public string P_VSPLICHTIG { get; set; }
        public string P_VERDOVINGSNUMMER { get; set; }
        public string P_APBZEGEL { get; set; }
        public string P_VERKOOPHOEV { get; set; }
        public string P_EIGENPRODUCT { get; set; }
        public string P_IS_KRUID { get; set; }
        public string P_IS_STOCKITEM { get; set; }
        public string P_UPDATECODE { get; set; }
        public Nullable<System.DateTime> P_DATUM_WIJZ { get; set; }
        public Nullable<System.DateTime> P_DATUM_PRIJSWIJZ { get; set; }
        public string P_IS_HOSPAK { get; set; }
        public string P_BIJSLUITER { get; set; }
        public Nullable<int> P_KRITIEKPUNT { get; set; }
        public Nullable<int> P_LEVNUM { get; set; }
        public Nullable<int> P_KRITIEKLEVNUM { get; set; }
        public Nullable<short> P_SCHRAPCODE { get; set; }
        public Nullable<int> P_VOORRAADPLAATS { get; set; }
        public string P_GEBRUIKVRAC { get; set; }
        public Nullable<int> P_LABO { get; set; }
        public Nullable<short> P_PRODUCTCODE { get; set; }
        public string P_BARCODE { get; set; }
        public string P_IN_TARIEF { get; set; }
        public Nullable<int> P_INBESTELLING { get; set; }
        public string P_IS_VERDOVING { get; set; }
        public Nullable<int> P_WACHTKOFFER { get; set; }
        public string P_YFORM { get; set; }
        public Nullable<decimal> P_WMARGE_AANKOOP { get; set; }
        public Nullable<decimal> P_WMARGE_VERKOOP { get; set; }
        public Nullable<short> P_REST_CODE { get; set; }
        public Nullable<short> P_STOCK_CODE { get; set; }
        public string P_HOMEO_AANVAARD { get; set; }
        public Nullable<int> P_RECHTSTR_LEVNUM { get; set; }
        public string P_RECHTSTREEKS { get; set; }
        public Nullable<int> P_UPDATEFLAGS { get; set; }
        public string P_GEBRUIK_IN_ZOEK { get; set; }
        public Nullable<short> P_AANT_MAANDEN { get; set; }
        public string P_HOE_VVD { get; set; }
        public Nullable<decimal> P_AANKOOP_PRIJS { get; set; }
        public string P_DRAAGT_UBC { get; set; }
        public string P_TARINFO { get; set; }
        public string P_DOPINGVL { get; set; }
        public string P_DOPINGFR { get; set; }
        public string P_MAG_IN_ROBOT { get; set; }
        public Nullable<int> P_ROBOT_STOCK { get; set; }
        public Nullable<decimal> P_REFPRIJS { get; set; }
        public string P_REGLET { get; set; }
        public Nullable<decimal> P_VERKOOPPRIJS_PERCENT { get; set; }
        public string P_GEENKORTING { get; set; }
        public string P_TEKST { get; set; }
        public string P_IN_WEBSHOP { get; set; }
        public string P_TEKST_PRIJSAANDUIDING { get; set; }
        public string P_BVAC { get; set; }
        public string P_URL { get; set; }
        public Nullable<int> P_LEVNUM_DRINGEND { get; set; }
        public int P_KLASSEOVERGANG { get; set; }
        public Nullable<int> P_AANTAL_DAGEN { get; set; }
        public decimal P_VERKOOPHOEV_NUM { get; set; }
        public int P_UDROBOT { get; set; }
        public string P_UNITDOSE { get; set; }
        public Nullable<decimal> P_GROEPSAANKOOPPRIJS { get; set; }
        public Nullable<decimal> P_GROEPSKORTING_PERCENT { get; set; }
        public Nullable<System.DateTime> P_GROEPSPRIJS_AANPASDATUM { get; set; }
        public string P_MANREX { get; set; }
        public Nullable<int> P_BESTELKLASSE_OPTIMAAL { get; set; }
        public string P_IS_DYNAMISCH { get; set; }
        public string P_SUBCAT { get; set; }
        public string P_TRANSTD { get; set; }
        public string P_IS_07NR { get; set; }
        public string P_IS_UDCNK { get; set; }
        public Nullable<decimal> P_AANKOOPPRIJS_UPDATE { get; set; }
        public string P_DIABETES { get; set; }
        public string P_ORIG { get; set; }
        public Nullable<int> P_BRON_PRIJS { get; set; }
        public string P_LAAGSTE_PRIJS { get; set; }
        public string P_OP_DOSIS_RPT { get; set; }
        public string P_HON_BASIS { get; set; }
        public Nullable<decimal> P_PRIJS_AF { get; set; }
        public Nullable<System.DateTime> P_DATUM_PRIJSDALING { get; set; }
        public string P_RVTPICKLIJSTOPNEMEN { get; set; }
        public Nullable<double> P_ACTIEFBESTANDDEEL { get; set; }
        public Nullable<double> P_INHOUD { get; set; }
        public Nullable<int> P_GALVORM_INDEX { get; set; }
        public string P_GEBRUIK { get; set; }
        public string P_CATAPB { get; set; }
        public string P_IS_BUITENLANDS { get; set; }
        public string P_MANUEEL_LOTNUMMER { get; set; }
        public Nullable<int> P_RIZIVCLUSTER { get; set; }
        public string P_GOEDKOOP { get; set; }
        public string P_SUBST_VERPLICHT { get; set; }
        public string P_NOOIT_KLANTSTOCK { get; set; }
        public string P_VOEDINGSSUP { get; set; }
        public string P_BNM { get; set; }
        public Nullable<decimal> P_AP_HUIDIG { get; set; }
        public Nullable<decimal> P_PP_HUIDIG { get; set; }
        public Nullable<decimal> P_AP_TOEK { get; set; }
        public Nullable<decimal> P_PP_TOEK { get; set; }
        public string P_TERUGBET_IN_BEREIDING { get; set; }
        public string P_IS_VERGUND { get; set; }
        public string P_HEEFT_ANALYSECERTIFICAAT { get; set; }
        public string P_VERGUNNINGSNUMMER { get; set; }
        public string P_VERBOD_VROEDVROUW { get; set; }
        public Nullable<decimal> P_KORTINGSPERCENT_AP { get; set; }
        public Nullable<int> P_HOE_AP_UPDATEN { get; set; }
        public string P_KLASSEOVERGANG_VRAAG_KLASSE1 { get; set; }
        public string P_WINKELDOCHTERS { get; set; }
        public Nullable<int> P_WINKELDOCHTERS_AANTAL { get; set; }
        public Nullable<System.DateTime> P_WINKELDOCHTERS_DATUMTIJD { get; set; }
        public string P_PIL_ID { get; set; }
        public string P_FORMULARIUM_ROBOT_IMPORT { get; set; }
        public string P_GROOTSTE_VERPAK { get; set; }
        public string P_COMBI { get; set; }
        public string P_VOORDELIGSTE { get; set; }
    }
}
