//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBPOSTCODES
    {
        public int PC_ID { get; set; }
        public string PC_NUMMER { get; set; }
        public string PC_GEMEENTE { get; set; }
        public string PC_VOL_NAAM { get; set; }
        public string PC_OCMW_NUMMER { get; set; }
    }
}
