//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBPOMSCHRIJVING
    {
        public string PT_CNKNUMMER { get; set; }
        public short PT_VOLGNUMMER { get; set; }
        public string PT_OMSCHRIJVING__ { get; set; }
        public string PT_OMSCHRIJVINGFR { get; set; }
        public string PT_SOUNDEX__ { get; set; }
        public string PT_SOUNDEXFR { get; set; }
        public string PT_ZOEK__ { get; set; }
        public string PT_ZOEKFR { get; set; }
        public string PT_KEY { get; set; }
    }
}
