//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBVERKOOPITEMS
    {
        public int VI_ID { get; set; }
        public int VI_VSNUMMER { get; set; }
        public string VI_CNKNUMMER { get; set; }
        public Nullable<short> VI_AANTAL_AFGELEV { get; set; }
        public Nullable<short> VI_AANTAL_AFTELEV { get; set; }
        public Nullable<decimal> VI_PUBLIEKSPRIJS { get; set; }
        public Nullable<decimal> VI_REMGELD { get; set; }
        public Nullable<decimal> VI_TEBETALEN { get; set; }
        public Nullable<decimal> VI_RESTORNO { get; set; }
        public Nullable<decimal> VI_KORTING { get; set; }
        public Nullable<int> VI_ATTESTID { get; set; }
        public string VI_TERUGBET_CAT { get; set; }
        public string VI_AFLEVERING { get; set; }
        public string VI_ISBETAALD { get; set; }
        public string VI_ISVERWERKT { get; set; }
        public string VI_ISSPECIAAL { get; set; }
        public string VI_CLASSNAME { get; set; }
        public Nullable<int> VI_PRODUCTCODE { get; set; }
        public Nullable<int> VI_AANTAL_GEFACT { get; set; }
        public Nullable<System.DateTime> VI_DATUM { get; set; }
        public Nullable<int> VI_RESTSTOCK { get; set; }
        public string VI_MAG_CNKNUMMER { get; set; }
        public string VI_ISUITGESTELD { get; set; }
        public string VI_GEENATTEST { get; set; }
        public string VI_UITSTELLING_AFGELEVERD { get; set; }
        public Nullable<decimal> VI_BEDRAG_OCMW { get; set; }
        public Nullable<decimal> VI_MAG_SPEC_BETAALBAAR { get; set; }
        public Nullable<int> VI_VARIA_ID { get; set; }
        public string VI_NIETOPFACTUUR { get; set; }
        public string VI_ISVERBETERING { get; set; }
        public Nullable<int> VI_POSOLOGIEID { get; set; }
        public string VI_UNIEKE_BC { get; set; }
        public string VI_ISVOS { get; set; }
        public Nullable<int> VI_PRIJSTYPE { get; set; }
        public string VI_OPFACTUUR { get; set; }
        public string VI_RESULTAAT_AEGATE { get; set; }
        public string VI_KREDIET_BLOKKEREN { get; set; }
        public Nullable<int> VI_KORTINGLOGIC { get; set; }
        public Nullable<decimal> VI_KORTING_PATIENT { get; set; }
        public string VI_TBVW_ANTW { get; set; }
        public string VI_EIGENBEDRAGOCMW { get; set; }
        public string VI_OCMW { get; set; }
        public string VI_AFSCHRIFT_OCMW { get; set; }
        public string VI_ORDERNR { get; set; }
        public int VI_ORDERLINEUID { get; set; }
        public string VI_IS_07NR { get; set; }
        public string VI_DIABETES { get; set; }
        public string VI_ZORGTRAJECT { get; set; }
        public string VI_HON_H4 { get; set; }
        public string VI_HON_1STE_UIT { get; set; }
        public string VI_HON_VOS { get; set; }
        public string VI_HON_BASIS { get; set; }
        public Nullable<decimal> VI_HON_H4_BEDRAG { get; set; }
        public Nullable<decimal> VI_HON_VOS_BEDRAG { get; set; }
        public Nullable<decimal> VI_HON_1STE_UIT_BEDRAG { get; set; }
        public Nullable<decimal> VI_HON_BEDRAG_OCMW { get; set; }
        public string VI_HON_CONTANT { get; set; }
        public string VI_SYNKEY { get; set; }
        public Nullable<decimal> VI_BEDRAG_BETAALD { get; set; }
        public Nullable<decimal> VI_BEDRAG_FACTUUR_BETAALD { get; set; }
        public Nullable<decimal> VI_BEDRAG_TEBETALEN { get; set; }
        public Nullable<decimal> VI_BEDRAG_FACTUUR_TEBETALEN { get; set; }
        public string VI_WEB { get; set; }
        public Nullable<int> VI_BETAALWIJZE { get; set; }
        public Nullable<int> VI_RBS_ID { get; set; }
        public Nullable<int> VI_PATIENTSTOCK { get; set; }
        public string VI_VET_VOEDSELPROD { get; set; }
        public string VI_NOMENCLATUUR { get; set; }
        public string VI_BANDAG_GEBRUIK { get; set; }
        public string VI_ISGRATIS { get; set; }
        public string VI_THERAP_BEZWAAR { get; set; }
        public string VI_SUBST_VERPLICHT { get; set; }
        public string VI_OVERMACHT { get; set; }
        public int VI_CONTANT { get; set; }
        public int VI_IMV { get; set; }
        public int VI_IMV_LEVERANCIER { get; set; }
        public Nullable<int> VI_LINKED_VERKOOPITEM { get; set; }
        public string VI_GFD_DGUID { get; set; }
        public string VI_GFD_SGUID { get; set; }
        public Nullable<int> A { get; set; }
        public Nullable<decimal> VI_TUSSENKOMST { get; set; }
        public Nullable<decimal> VI_RESTORNO_GEGEVEN { get; set; }
        public Nullable<decimal> VI_RESTORNO_ON_RESTORNO { get; set; }
        public Nullable<int> VI_KLANTNUMMER { get; set; }
        public string VI_ISDOORFACTURATIE { get; set; }
        public Nullable<decimal> VI_AANKOOPPRIJS { get; set; }
        public Nullable<int> VI_FACTGROEP_ID { get; set; }
        public Nullable<decimal> VI_WINST { get; set; }
        public Nullable<decimal> VI_BTWPERCENT { get; set; }
        public Nullable<decimal> VI_BTWPERCENT_USED { get; set; }
        public int VI_TYPE { get; set; }
        public string VI_UITSTOCK { get; set; }
        public Nullable<int> VI_SESSIE { get; set; }
        public Nullable<int> VI_AANTAL_KEER_GEFACT { get; set; }
        public string VI_MAF { get; set; }
        public Nullable<decimal> VI_AANTAL_PILLEN_TOTAAL { get; set; }
        public Nullable<decimal> VI_AANTAL_PILLEN_RESTEREND { get; set; }
        public string VI_TPE_FLAG1 { get; set; }
        public Nullable<short> VI_TPE_TYPE { get; set; }
        public string VI_ISAANGEREKEND { get; set; }
    }
}
