//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTBVERKOPEN
    {
        public int V_VERKOOPSID { get; set; }
        public System.DateTime V_AFLEVERDATUM { get; set; }
        public decimal V_KORTING { get; set; }
        public string V_RESTNUMMER { get; set; }
        public string V_RESTBETAALD { get; set; }
        public decimal V_BEDR_BETAALD { get; set; }
        public decimal V_RESTORNO { get; set; }
        public decimal V_CASH { get; set; }
        public decimal V_PROTON { get; set; }
        public decimal V_CREDITCARD { get; set; }
        public decimal V_BANCONTACT { get; set; }
        public int V_KORTINGPERCENTAGE { get; set; }
        public Nullable<int> V_BETALER { get; set; }
        public Nullable<int> V_SPAARREKENINGID { get; set; }
        public string V_SPAARKAARTGELEZEN { get; set; }
        public decimal V_BANK { get; set; }
        public int V_FACTUURNR { get; set; }
        public string V_COMPUTER { get; set; }
        public string V_GEBRUIKER { get; set; }
        public decimal V_EXTERNEBETALING { get; set; }
        public Nullable<short> V_TYPE { get; set; }
    }
}
