//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenockUsers
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string ShortUserName { get; set; }
        public string Password { get; set; }
        public string TemplateBiometric { get; set; }
        public Nullable<int> UserCID { get; set; }
    }
}
