//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HvtNames
    {
        public int ArtIdCPCL { get; set; }
        public int NameNr { get; set; }
        public string LangCode { get; set; }
        public string ArtName { get; set; }
        public Nullable<int> GreenockID { get; set; }
    
        public virtual Hvts Hvts { get; set; }
    }
}
