//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HvtQtyPrices
    {
        public int ArtHvtID { get; set; }
        public string HvtQtyCode { get; set; }
        public decimal HvtQtd { get; set; }
        public decimal PubPrice { get; set; }
    
        public virtual Hvts Hvts { get; set; }
    }
}
