//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsrCovers
    {
        public int InsrCoverId { get; set; }
        public int PatIdCPCL { get; set; }
        public Nullable<System.DateTime> DateRead { get; set; }
        public int Nsuite { get; set; }
        public string FedNr { get; set; }
        public bool IsOaviExist { get; set; }
        public string RegistrationNr { get; set; }
        public string CgctCt1Cpy { get; set; }
        public string CgctCt2Cpy { get; set; }
        public string SisCardNr { get; set; }
        public Nullable<System.DateTime> DateActiveStart { get; set; }
        public Nullable<System.DateTime> DateActiveEnd { get; set; }
        public Nullable<System.DateTime> DateValidityEnd { get; set; }
        public Nullable<System.DateTime> DateValidityStart { get; set; }
        public string Siscertificate { get; set; }
        public Nullable<bool> IsAttestSIS { get; set; }
        public Nullable<decimal> SochelpThresholdAmnt { get; set; }
        public Nullable<int> SochelpThresholdType { get; set; }
        public string OaviCode { get; set; }
        public string InsrCatCode { get; set; }
        public Nullable<int> GreenockID { get; set; }
        public Nullable<int> OaviVersion { get; set; }
        public Nullable<System.DateTime> DateOrdo { get; set; }
        public string Periode { get; set; }
        public Nullable<short> InsrCoverSource { get; set; }
    }
}
