//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelEditorLocs
    {
        public string LabelEditorLocCode { get; set; }
        public string LabelEditorLocLabel { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<int> GreenockID { get; set; }
    
        public virtual Warehouses Warehouses { get; set; }
    }
}
