//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalizationStock
    {
        public int StockIDCPCL { get; set; }
        public string WarehouseCode { get; set; }
        public string LocalisationCode { get; set; }
        public int Stock { get; set; }
        public Nullable<int> MinThd { get; set; }
        public Nullable<int> MaxThd { get; set; }
        public Nullable<int> UnitOrder { get; set; }
        public Nullable<int> GreenockID { get; set; }
    
        public virtual Localization Localization { get; set; }
    }
}
