//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magistrals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magistrals()
        {
            this.MagItems = new HashSet<MagItems>();
            this.SaleItems = new HashSet<SaleItems>();
        }
    
        public int MagistralID { get; set; }
        public string MagistralNr { get; set; }
        public string MagistralName { get; set; }
        public System.DateTime DateMag { get; set; }
        public string GalformCode { get; set; }
        public Nullable<int> DtQty { get; set; }
        public string UnitCodePresb { get; set; }
        public Nullable<decimal> PresbQtd { get; set; }
        public decimal BaseAmntNetto { get; set; }
        public decimal MagFullPrice { get; set; }
        public decimal AmntChem { get; set; }
        public decimal AmntChemReimb { get; set; }
        public decimal AmntExcipient { get; set; }
        public decimal AmntExcipientReimb { get; set; }
        public int ModCount { get; set; }
        public int ReimbModCount { get; set; }
        public decimal AmntHon { get; set; }
        public decimal AmntHonReimb { get; set; }
        public int RgtmCount { get; set; }
        public decimal UnitPriceRgtm { get; set; }
        public string RgtmType { get; set; }
        public Nullable<decimal> CoeffReductQtd { get; set; }
        public Nullable<decimal> CoeffReductDt { get; set; }
        public string MagCalcMethodCode { get; set; }
        public Nullable<short> IsNasalUse { get; set; }
        public short IsReimbHomeo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MagItems> MagItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItems> SaleItems { get; set; }
    }
}
