//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagItems
    {
        public int MagistralID { get; set; }
        public int MitmNr { get; set; }
        public Nullable<int> SlsID { get; set; }
        public Nullable<int> SsecNr { get; set; }
        public Nullable<int> SitmNr { get; set; }
        public string MagItemType { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> Thirdpartypaid { get; set; }
        public Nullable<decimal> AmntNetto { get; set; }
        public Nullable<decimal> FullPrice { get; set; }
        public Nullable<int> ArtIDSold { get; set; }
        public Nullable<decimal> Qtd { get; set; }
        public string QtdUnitCode { get; set; }
        public Nullable<int> QtyQualifier { get; set; }
        public string FormType { get; set; }
        public Nullable<int> FormID { get; set; }
        public string LegConstrListCpy { get; set; }
        public string SpecHonCode { get; set; }
        public int RecrsDepth { get; set; }
        public Nullable<short> IsAntioxidant { get; set; }
        public Nullable<int> InamirizivListNr { get; set; }
        public Nullable<int> ArtIDFromStock { get; set; }
        public Nullable<int> DeliveredQty { get; set; }
        public int ArtIdSoldType { get; set; }
        public string ArtReimbCatCode { get; set; }
        public string ReimbExcptCode { get; set; }
        public short IsAttestNeeded { get; set; }
        public Nullable<int> AttestID { get; set; }
        public short IsAttestMissing { get; set; }
        public short IsReimbMarkNeeded { get; set; }
        public Nullable<int> ArtReimbMarkCode { get; set; }
        public short IsStampNeeded { get; set; }
        public short HasStamp { get; set; }
    
        public virtual Magistrals Magistrals { get; set; }
    }
}
