//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParameterTypes()
        {
            this.ParameterLabels = new HashSet<ParameterLabels>();
        }
    
        public string ParameterType { get; set; }
        public short SortNr { get; set; }
        public bool Offigest { get; set; }
        public bool Isa { get; set; }
        public bool Farmix { get; set; }
        public Nullable<int> ParamInteger { get; set; }
        public Nullable<decimal> ParamDecimal { get; set; }
        public Nullable<System.DateTime> ParamDate { get; set; }
        public Nullable<bool> ParamBoolean { get; set; }
        public string ParamText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParameterLabels> ParameterLabels { get; set; }
    }
}
