//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public string PharmacyName { get; set; }
        public string SoftName { get; set; }
        public string Address { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public string APBNr { get; set; }
        public string PharmacyOrderNr { get; set; }
        public string RIZIVNr { get; set; }
        public string PhoneNr { get; set; }
        public string FaxNr { get; set; }
        public string GSMNr { get; set; }
        public string Email { get; set; }
        public string BanckAccNr { get; set; }
        public string BanckAccNr2 { get; set; }
        public string CommercialNr { get; set; }
        public string VatNr { get; set; }
        public string Langcode { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<int> LastNrSale { get; set; }
        public string InportExportVersion { get; set; }
        public Nullable<int> LastInvoiceNr { get; set; }
    }
}
