//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int PatIdCPCL { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FirstName2 { get; set; }
        public string NissinszNr { get; set; }
        public string Address { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string GSM { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string GenderCode { get; set; }
        public string LangCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PrescriberID { get; set; }
        public Nullable<System.DateTime> LastDateSale { get; set; }
        public Nullable<int> PatIDFamilly { get; set; }
        public Nullable<int> F704PrintType { get; set; }
        public Nullable<int> CblPrintType { get; set; }
        public string BlocNr { get; set; }
        public string FloorNr { get; set; }
        public string RoomNr { get; set; }
        public string Deceased { get; set; }
        public Nullable<int> GreenockID { get; set; }
        public Nullable<int> ActorCID { get; set; }
        public string Memo { get; set; }
        public Nullable<int> RecuPrintType { get; set; }
        public Nullable<int> BVACPrintType { get; set; }
        public Nullable<int> PatLink { get; set; }
        public string CustRistGrpCode { get; set; }
        public string PaymMethodType { get; set; }
        public Nullable<short> IsIvc { get; set; }
        public Nullable<short> IsMultidose { get; set; }
    }
}
