//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymMethods1
    {
        public string PaymMethodCode { get; set; }
        public decimal PaymMethodCost { get; set; }
        public int RegSortNr { get; set; }
        public int RegSheetDirectionType { get; set; }
        public Nullable<short> IsShowRegSheet { get; set; }
        public decimal PaymMethodCostMinAmnt { get; set; }
        public Nullable<short> IsEft { get; set; }
        public int PaymMethodCostType { get; set; }
    }
}
