//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymEftBreakds
    {
        public int RegTransactID { get; set; }
        public string PaymMethodCode { get; set; }
        public string CurrencyIsoCodeCust { get; set; }
        public string EftTerminalName { get; set; }
        public string EftTermID { get; set; }
        public Nullable<decimal> EftTxvictxamt { get; set; }
        public Nullable<int> EftAppid { get; set; }
        public string EftCardID { get; set; }
        public string EftVictxid { get; set; }
        public string EftPdvclctnr { get; set; }
        public string EftPdvgentxnb { get; set; }
        public string EftEmvcvm { get; set; }
        public string EftEmvdatetime { get; set; }
        public string EftEmvtransid { get; set; }
        public System.DateTime DatePaymEft { get; set; }
    }
}
