//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peremption
    {
        public System.DateTime PeremptionDate { get; set; }
        public string LotNr { get; set; }
        public int ArtIdCPCL { get; set; }
        public string CNKNr { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> GreenockID { get; set; }
    }
}
