//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacies
    {
        public int PharmID { get; set; }
        public string TitulName { get; set; }
        public string ImsCode { get; set; }
        public string PharmApbNr { get; set; }
        public string PharmApbNrSuffix { get; set; }
        public string InamirizvNr { get; set; }
        public short TdpPharmID { get; set; }
        public string EmailTaroffice { get; set; }
        public string TradeRegstNr { get; set; }
        public Nullable<int> PlaceIDTradeRegst { get; set; }
        public string ISAcod_perm_db { get; set; }
        public int TarProtVersionNr { get; set; }
        public System.DateTime DateTarProtVersionStart { get; set; }
        public string RprrpmNr { get; set; }
        public string GroupType { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string PharmacyName { get; set; }
        public string Address { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string GSM { get; set; }
        public string Email { get; set; }
        public string LangCode { get; set; }
        public string CurrencyIsoCodeCust { get; set; }
    }
}
