//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmDocDataLabels
    {
        public int PharmID { get; set; }
        public string PharmaDocType { get; set; }
        public string LangCode { get; set; }
        public string Name { get; set; }
        public string Chksum { get; set; }
        public string Address { get; set; }
        public string TelNr { get; set; }
        public string FaxNr { get; set; }
        public string RebateLabel { get; set; }
        public string RistPrefixLabel { get; set; }
        public string RistSuffixLabel { get; set; }
        public string HeaderLabel { get; set; }
        public string FooterLabel { get; set; }
    
        public virtual PharmDocDatas PharmDocDatas { get; set; }
    }
}
