//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmDocDatas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PharmDocDatas()
        {
            this.PharmDocDataLabels = new HashSet<PharmDocDataLabels>();
        }
    
        public int PharmID { get; set; }
        public string PharmaDocType { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
        public string ImageFilename { get; set; }
        public int ImageWidth { get; set; }
        public int ImageHeight { get; set; }
        public string RebateToken { get; set; }
        public string RistToken { get; set; }
        public byte[] PharmImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmDocDataLabels> PharmDocDataLabels { get; set; }
    }
}
