//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescribers
    {
        public int PrescriberIDCPCL { get; set; }
        public string PrescriberName { get; set; }
        public string InamirizvNr { get; set; }
        public string Address { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public string phone { get; set; }
        public string GSM { get; set; }
        public string Email { get; set; }
        public Nullable<int> GreenockID { get; set; }
        public Nullable<short> IsPrespTheft { get; set; }
        public Nullable<System.DateTime> DatePrespTheft { get; set; }
        public string PresbProfCode { get; set; }
        public string Fax { get; set; }
        public string Memo { get; set; }
        public string CustRistGrpCode { get; set; }
    }
}
