//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInOrder
    {
        public int CustomerID { get; set; }
        public System.DateTime Date { get; set; }
        public int ArtIdCPCL { get; set; }
        public string CNKNr { get; set; }
        public Nullable<int> QtySend { get; set; }
        public Nullable<int> OrderNr { get; set; }
        public string FreeText { get; set; }
        public Nullable<int> GreenockID { get; set; }
    }
}
