//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public string PharmApbNr { get; set; }
        public Nullable<System.DateTime> TimeCallCorilus { get; set; }
        public string CorilusLicenseCode { get; set; }
        public string GroupType { get; set; }
        public string DBIID { get; set; }
        public string WsAccount { get; set; }
        public string WsPassword { get; set; }
        public string PermissionCode { get; set; }
        public string Permissions { get; set; }
    }
}
