//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegTransactions
    {
        public int RegTransactID { get; set; }
        public System.DateTime DateTimeTransact { get; set; }
        public string RegTransactType { get; set; }
        public decimal TotalAmntIn { get; set; }
        public Nullable<decimal> TotalAmntVatex { get; set; }
        public decimal TotalAmntOut { get; set; }
        public string RegisterCode { get; set; }
        public int RegSessionNr { get; set; }
        public string Memo { get; set; }
        public Nullable<int> PendingID { get; set; }
        public Nullable<int> SlsID { get; set; }
        public string CurrencyIsoCodeCust { get; set; }
        public short IsIvc { get; set; }
        public Nullable<short> CentralizationStatus { get; set; }
    }
}
