//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnAwaitings
    {
        public int ReturnAwaitingID { get; set; }
        public string ReturnType { get; set; }
        public System.DateTime DateReturn { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Memo { get; set; }
        public int ArtID { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> BuyPricePerUnit { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public string LotNr { get; set; }
        public string WrkstatCode { get; set; }
    }
}
