//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RistCards
    {
        public string CardNr { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> CustIdCPCL { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<bool> CardStatus { get; set; }
        public Nullable<int> GreenockID { get; set; }
        public Nullable<short> CentralizationStatus { get; set; }
    }
}
