//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RistCardsAccounts
    {
        public int RcAccountID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string CustRistGrpCode { get; set; }
        public string ReleaseType { get; set; }
        public string ReleaseLimit { get; set; }
        public int RcAccStatusType { get; set; }
        public Nullable<int> GreenockID { get; set; }
        public Nullable<int> RcAccountCID { get; set; }
        public Nullable<short> CentralizationStatus { get; set; }
    }
}
