//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RistCardsRists
    {
        public int UniqueId { get; set; }
        public string RistCardNr { get; set; }
        public System.DateTime DatetimeFirst { get; set; }
        public decimal VatRate { get; set; }
        public decimal AmntRist { get; set; }
        public string RistTransactType { get; set; }
        public Nullable<int> SlsID { get; set; }
        public Nullable<short> CentralizationStatus { get; set; }
    }
}
