//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RistCustRules
    {
        public int RistRuleID { get; set; }
        public decimal RistPercent { get; set; }
        public string RistType { get; set; }
        public short LimitType { get; set; }
        public Nullable<decimal> AmntMax { get; set; }
        public Nullable<int> RistNonReimbType { get; set; }
        public int PharmID { get; set; }
        public int PushStatusType { get; set; }
        public Nullable<System.DateTime> DateLastPush { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<System.DateTime> DateLastChange { get; set; }
        public Nullable<byte> Deleted { get; set; }
    }
}
