//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleSections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleSections()
        {
            this.SaleItems = new HashSet<SaleItems>();
        }
    
        public int SlsID { get; set; }
        public int SsecNr { get; set; }
        public string SectionType { get; set; }
        public Nullable<int> PrescriptionNr { get; set; }
        public System.DateTime DateDeliv { get; set; }
        public Nullable<System.DateTime> DatePresp { get; set; }
        public Nullable<int> PatID { get; set; }
        public Nullable<int> PrescriberID { get; set; }
        public Nullable<bool> HonUrg { get; set; }
        public Nullable<decimal> PriceHonUrg { get; set; }
        public string Oxygene { get; set; }
        public string CertificatSIS { get; set; }
        public Nullable<int> RenewalNr { get; set; }
        public string InamirizvNrCpy { get; set; }
        public string PresbSpecCodeCpy { get; set; }
        public bool IsTariffing { get; set; }
        public Nullable<System.DateTime> DateIsTar { get; set; }
        public short IsWaitingTaroffice { get; set; }
        public string WaittingTarofficeReason { get; set; }
        public short IsBackofficeMode { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
        public Nullable<int> InsrCoverID { get; set; }
        public Nullable<int> InsrCoverSecondID { get; set; }
        public Nullable<short> IsSisCardMissing { get; set; }
        public Nullable<System.DateTime> DateStartOxygen { get; set; }
        public Nullable<System.DateTime> DateStopOxygen { get; set; }
        public Nullable<decimal> FlowOxygen { get; set; }
        public Nullable<int> DelivTypeOxygen { get; set; }
        public Nullable<System.TimeSpan> DailyAmntOxygen { get; set; }
        public Nullable<System.DateTime> DatetimeSisRead { get; set; }
        public Nullable<System.DateTime> DateMaxDeliv { get; set; }
        public Nullable<System.DateTime> DateMaxReimb { get; set; }
        public string CertificateSeed { get; set; }
        public string OttdCheckDigits { get; set; }
        public Nullable<short> IsMyCareNetBackup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItems> SaleItems { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Sales Sales1 { get; set; }
    }
}
