//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePoso
    {
        public int SlsID { get; set; }
        public int SaleSectionID { get; set; }
        public int LignNr { get; set; }
        public string text { get; set; }
    
        public virtual SaleItems SaleItems { get; set; }
    }
}
