//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.SaleSections = new HashSet<SaleSections>();
            this.SaleSections1 = new HashSet<SaleSections>();
        }
    
        public int SlsID { get; set; }
        public Nullable<int> SaleTicketNr { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsInvoiced { get; set; }
        public string InvoiceNr { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> PrintInvoiceDate { get; set; }
        public System.DateTime DateSale { get; set; }
        public string WrkstatCode { get; set; }
        public decimal AmntRebate { get; set; }
        public decimal AmntRist { get; set; }
        public decimal AmntNetto { get; set; }
        public decimal AmntPaid { get; set; }
        public string CurrencyIsoCodeCust { get; set; }
        public short IsBackofficeMode { get; set; }
        public System.DateTime TimeSaleStart { get; set; }
        public Nullable<System.DateTime> TimeTicketPrinted { get; set; }
        public Nullable<int> GreenockID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleSections> SaleSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleSections> SaleSections1 { get; set; }
    }
}
