//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleItems()
        {
            this.SitmUbcs = new HashSet<SitmUbcs>();
            this.SitmHons = new HashSet<SitmHons>();
        }
    
        public int SlsID { get; set; }
        public int SsecNr { get; set; }
        public int SitmNr { get; set; }
        public Nullable<int> ArtID { get; set; }
        public Nullable<int> MagistralID { get; set; }
        public Nullable<decimal> PubPricePerUnit { get; set; }
        public Nullable<decimal> BuyPriceEstmPerUnit { get; set; }
        public Nullable<int> SaleQty { get; set; }
        public Nullable<int> AttestID { get; set; }
        public Nullable<int> OriginalPrescpNr { get; set; }
        public Nullable<bool> Dci { get; set; }
        public string ClusterID { get; set; }
        public string SitmType { get; set; }
        public string Memo { get; set; }
        public string SitmRegulType { get; set; }
        public string PendType { get; set; }
        public Nullable<decimal> VatRateCpy { get; set; }
        public Nullable<int> DeliveredQty { get; set; }
        public Nullable<int> ReservedQty { get; set; }
        public Nullable<int> PayableQty { get; set; }
        public string RistType { get; set; }
        public Nullable<decimal> Thirdpartypaid { get; set; }
        public Nullable<decimal> AmntNetto { get; set; }
        public Nullable<int> ArtIDFromStock { get; set; }
        public Nullable<decimal> Qtd { get; set; }
        public string LegConstrListCpy { get; set; }
        public short IsBackofficeMode { get; set; }
        public Nullable<decimal> AmntPaid { get; set; }
        public decimal AmntRist { get; set; }
        public decimal AmntRebate { get; set; }
        public Nullable<decimal> AmntRistNetto { get; set; }
        public Nullable<decimal> AmntRebateNetto { get; set; }
        public int PaidQty { get; set; }
        public int UnpaidDeliveredQty { get; set; }
        public int RenewalCount { get; set; }
        public Nullable<int> RenewalNr { get; set; }
        public Nullable<int> RenewalPeriodCount { get; set; }
        public string RenewalPeriodType { get; set; }
        public Nullable<short> IsTdpTarTrf { get; set; }
        public Nullable<short> IsTdpIvcTrfs { get; set; }
        public Nullable<decimal> BasepricePerUnit { get; set; }
        public Nullable<decimal> AmntRistPat { get; set; }
        public Nullable<decimal> AmntRebatePat { get; set; }
        public Nullable<decimal> AmntRistPatNetto { get; set; }
        public Nullable<decimal> AmntRebatePatNetto { get; set; }
        public int DeferredDeliveryQty { get; set; }
        public Nullable<short> F704PrintType { get; set; }
        public Nullable<short> BvacPrintType { get; set; }
        public Nullable<short> IsSubst { get; set; }
        public string ArtReimbCatCode { get; set; }
        public string ReimbExcptCode { get; set; }
        public Nullable<short> IsReimbMarkNeeded { get; set; }
        public Nullable<short> IsStampNeeded { get; set; }
        public int RgtmCount { get; set; }
        public Nullable<decimal> AmntPaidSecondCover { get; set; }
        public Nullable<int> pendingResolve { get; set; }
        public Nullable<short> IsAttestMissing { get; set; }
        public Nullable<int> UnDeliveredQty { get; set; }
        public Nullable<short> IsFirstDeliv { get; set; }
        public Nullable<int> DeferredDeliveryType { get; set; }
        public Nullable<int> SupplPackageQty { get; set; }
        public Nullable<short> InnSubstPrescType { get; set; }
        public Nullable<int> RgtmCountReimbursable { get; set; }
    
        public virtual Magistrals Magistrals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitmUbcs> SitmUbcs { get; set; }
        public virtual SaleSections SaleSections { get; set; }
        public virtual SalePoso SalePoso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitmHons> SitmHons { get; set; }
    }
}
