//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitmHons
    {
        public int SlsID { get; set; }
        public int SsecNr { get; set; }
        public int SitmNr { get; set; }
        public int SeqNr { get; set; }
        public string SitmHonType { get; set; }
        public Nullable<int> ArtID { get; set; }
        public Nullable<decimal> HonPrice { get; set; }
        public Nullable<decimal> AmntHonThirdpartypaid { get; set; }
        public int Quantity { get; set; }
    
        public virtual SaleItems SaleItems { get; set; }
    }
}
