//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int ArtIDCPCL { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public string CNK { get; set; }
        public Nullable<int> StatisticBuy { get; set; }
        public Nullable<int> StatisticSell { get; set; }
        public Nullable<int> GreenockID { get; set; }
    }
}
