//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public int ArtIdCPCL { get; set; }
        public Nullable<int> QtyInStock { get; set; }
        public Nullable<int> OnOrderQty { get; set; }
        public Nullable<int> ExtraOrderQty { get; set; }
        public Nullable<int> ReservedQty { get; set; }
        public Nullable<short> IsAllowThresholdChange { get; set; }
        public int MinThd { get; set; }
        public int MaxThd { get; set; }
        public int OrderPromoQty { get; set; }
        public int OrderStatusType { get; set; }
        public Nullable<System.DateTime> DateTimeShortageEnd { get; set; }
        public Nullable<decimal> MaxThdCalc { get; set; }
        public Nullable<System.DateTime> DateFirstReceipt { get; set; }
        public Nullable<decimal> AvgStock { get; set; }
        public Nullable<short> IsTdpWaitingTrf { get; set; }
        public Nullable<decimal> BuyPriceWeighted { get; set; }
        public Nullable<int> OnOrderRepresQty { get; set; }
        public Nullable<System.DateTime> DateLastSale { get; set; }
        public Nullable<int> greenockID { get; set; }
        public string AllowUdPubPriceChangeType { get; set; }
        public Nullable<int> SupplierIDPref { get; set; }
        public Nullable<int> SupplierIDNextOrder { get; set; }
    }
}
