//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLog
    {
        public int StockLogID { get; set; }
        public string StockChangeCode { get; set; }
        public string StockChangeReasonCode { get; set; }
        public System.DateTime DateLog { get; set; }
        public int UID { get; set; }
        public string WrkstatCode { get; set; }
        public int ArtIdCPCL { get; set; }
        public Nullable<int> QtyInStock_Before { get; set; }
        public Nullable<int> OnOrderQty_Before { get; set; }
        public Nullable<int> ExtraOrderQty_Before { get; set; }
        public Nullable<int> ReservedQty_Before { get; set; }
        public Nullable<short> IsAllowThresholdChange_Before { get; set; }
        public Nullable<int> MinThd_Before { get; set; }
        public Nullable<int> MaxThd_Before { get; set; }
        public Nullable<int> OrderPromoQty_Before { get; set; }
        public Nullable<int> OrderStatusType_Before { get; set; }
        public Nullable<System.DateTime> DateTimeShortageEnd_Before { get; set; }
        public Nullable<decimal> MaxThdCalc_Before { get; set; }
        public Nullable<decimal> AvgStock_Before { get; set; }
        public Nullable<decimal> BuyPriceWeighted_Before { get; set; }
        public Nullable<int> QtyInStock_After { get; set; }
        public Nullable<int> OnOrderQty_After { get; set; }
        public Nullable<int> ExtraOrderQty_After { get; set; }
        public Nullable<int> ReservedQty_After { get; set; }
        public Nullable<short> IsAllowThresholdChange_After { get; set; }
        public Nullable<int> MinThd_After { get; set; }
        public Nullable<int> MaxThd_After { get; set; }
        public Nullable<int> OrderPromoQty_After { get; set; }
        public Nullable<int> OrderStatusType_After { get; set; }
        public Nullable<System.DateTime> DateTimeShortageEnd_After { get; set; }
        public Nullable<decimal> MaxThdCalc_After { get; set; }
        public Nullable<decimal> AvgStock_After { get; set; }
        public Nullable<decimal> BuyPriceWeighted_After { get; set; }
        public Nullable<System.DateTime> DateFirstReceipt { get; set; }
        public Nullable<int> SlsID { get; set; }
        public Nullable<int> OrdID { get; set; }
        public Nullable<System.DateTime> DateLastSale_Before { get; set; }
        public Nullable<System.DateTime> DateLastSale_After { get; set; }
        public Nullable<short> CentralizationStatus { get; set; }
        public Nullable<int> RescueThd_Before { get; set; }
        public Nullable<int> RescueThd_After { get; set; }
    }
}
