//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public int SupplierIDCPCL { get; set; }
        public string SupplierName { get; set; }
        public string PhoneNr1 { get; set; }
        public string PhoneNr2 { get; set; }
        public string PasswordBIDI { get; set; }
        public string Protocole { get; set; }
        public string SupplierCode { get; set; }
        public string UrlIbotp1 { get; set; }
        public string UrlIbotp2 { get; set; }
        public string LogginIbotp { get; set; }
        public string PasswordIbotp { get; set; }
        public Nullable<int> GreenockID { get; set; }
        public string SupplierType { get; set; }
        public string ContactName { get; set; }
        public string LabApbCode { get; set; }
        public string Memo { get; set; }
        public string ContactPhoneNr { get; set; }
        public string ContactEmail { get; set; }
        public string OrderMemo { get; set; }
        public string ISAcod_typ_maj_fou { get; set; }
        public Nullable<short> ISAis_gest_art_fou { get; set; }
        public string AssemblyOrderType { get; set; }
        public string FilterText { get; set; }
        public Nullable<short> SuppPrefFilter { get; set; }
        public Nullable<short> StupFilter { get; set; }
        public Nullable<short> MissingFilter { get; set; }
        public Nullable<short> IsExpensiveFilter { get; set; }
        public Nullable<short> IsReservedFilter { get; set; }
        public Nullable<short> WarehouseFilter { get; set; }
        public string Address { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<int> OriginalID { get; set; }
        public Nullable<int> ActorCID { get; set; }
    }
}
