//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskTypes()
        {
            this.TaskLabels = new HashSet<TaskLabels>();
        }
    
        public string TaskType { get; set; }
        public int SortNr { get; set; }
        public string GroupType { get; set; }
        public short Checked { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<int> NbrMonths { get; set; }
        public int MaxErrorPercent { get; set; }
    
        public virtual TaskGroupTypes TaskGroupTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskLabels> TaskLabels { get; set; }
    }
}
