//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlTypes
    {
        public string UrlName { get; set; }
        public string Url { get; set; }
        public string UrlParams { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int TimeOut { get; set; }
        public short IsUpdatable { get; set; }
        public Nullable<int> PortNr { get; set; }
    }
}
