//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string LangCode { get; set; }
        public string Memo { get; set; }
        public int UID { get; set; }
        public string UxName { get; set; }
        public short IsLeftHanded { get; set; }
        public string TicketNickname { get; set; }
        public string LastName { get; set; }
        public string ImageName { get; set; }
        public byte[] UserImage { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> UserCID { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> SysUID { get; set; }
        public string NissinszNr { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastSynchroDateTime { get; set; }
        public string AppUserPassword { get; set; }
        public byte[] CRC { get; set; }
        public Nullable<System.DateTime> DateLastChange { get; set; }
        public Nullable<int> UIDLastChange { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual UserEmails UserEmails { get; set; }
    }
}
