//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmails
    {
        public int UID { get; set; }
        public string Email { get; set; }
        public int IsSelected { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
