//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int MajorNr { get; set; }
        public Nullable<int> MinorNr { get; set; }
        public Nullable<int> RevisionNr { get; set; }
        public Nullable<System.DateTime> LastUpgradeDate { get; set; }
        public int DatabaseStatus { get; set; }
    }
}
