//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhLocs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WhLocs()
        {
            this.WhLocationLabels = new HashSet<WhLocationLabels>();
        }
    
        public string WhLocCode { get; set; }
        public int WhID { get; set; }
        public int WhLocId { get; set; }
        public string LocHorizontalPos { get; set; }
        public Nullable<int> LocVerticalPos { get; set; }
        public Nullable<int> LocWidth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WhLocationLabels> WhLocationLabels { get; set; }
    }
}
