//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdDepTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WithdDepTypes()
        {
            this.WithdDeps = new HashSet<WithdDeps>();
        }
    
        public string WithdDepCode { get; set; }
        public string AccySchemeNr { get; set; }
        public Nullable<short> IsShowIvcReference { get; set; }
        public Nullable<short> IsShowAccySchemeNr { get; set; }
        public int WithdDepDirectionType { get; set; }
        public string WithdDepLabel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdDeps> WithdDeps { get; set; }
    }
}
