//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdDeps
    {
        public int RegTransactID { get; set; }
        public string WithdDepCode { get; set; }
        public string TdpIvcReference { get; set; }
        public string AccyNr { get; set; }
        public Nullable<System.DateTime> DateWithdDep { get; set; }
        public Nullable<int> IvcID { get; set; }
        public Nullable<int> PaymSeqNr { get; set; }
    
        public virtual WithdDepTypes WithdDepTypes { get; set; }
    }
}
