//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workstations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workstations()
        {
            this.WorkstationDevices = new HashSet<WorkstationDevices>();
        }
    
        public string WrkstatCode { get; set; }
        public string WrkstatDescrText { get; set; }
        public string KeyboardCode { get; set; }
        public string RegisterCode { get; set; }
        public Nullable<int> TicketPrinterID { get; set; }
        public Nullable<int> FormPrinterID { get; set; }
        public Nullable<int> ListPrinterID { get; set; }
        public Nullable<int> CardPrinterID { get; set; }
        public Nullable<int> LabelCompositePrinterID { get; set; }
        public Nullable<int> LabelContinuPrinterID { get; set; }
        public Nullable<int> LabelPluralPrinterID { get; set; }
        public Nullable<int> LabelSinglePrinterID { get; set; }
        public Nullable<int> SlipPrinterID { get; set; }
        public Nullable<int> ScreenID { get; set; }
        public Nullable<int> SisReaderID { get; set; }
        public Nullable<int> EftID { get; set; }
        public Nullable<int> CashDrawerID { get; set; }
        public Nullable<int> ModemID { get; set; }
        public Nullable<int> RobotID { get; set; }
        public Nullable<int> EidReaderID { get; set; }
        public Nullable<int> PaperScanID { get; set; }
        public bool Active { get; set; }
        public Nullable<int> BarcodeReaderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkstationDevices> WorkstationDevices { get; set; }
    }
}
