//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkstationDevices
    {
        public int WrkstatDeviceID { get; set; }
        public string WrkstatCode { get; set; }
        public int DeviceID { get; set; }
    
        public virtual WrkstatBackups WrkstatBackups { get; set; }
        public virtual WrkstatCashDrawers WrkstatCashDrawers { get; set; }
        public virtual Workstations Workstations { get; set; }
        public virtual WrkstatEfts WrkstatEfts { get; set; }
        public virtual WrkstatEidReaders WrkstatEidReaders { get; set; }
        public virtual WrkstatModems WrkstatModems { get; set; }
        public virtual WrkstatPrinters WrkstatPrinters { get; set; }
        public virtual WrkstatRobots WrkstatRobots { get; set; }
        public virtual WrkstatScreens WrkstatScreens { get; set; }
        public virtual WrkstatSisReaders WrkstatSisReaders { get; set; }
    }
}
