//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrkstatBarcodeReaders
    {
        public int WrkstatDeviceID { get; set; }
        public string PreAmble { get; set; }
        public string PostAmble { get; set; }
        public string ConfigType { get; set; }
    }
}
